variables:
  # Replace this name with that of the Azure service connection in your DevOps project
  ConnectedServiceName: 'Azure Primary'

  # Replace this name to match the name of the App Service you created earlier
  WebAppName: 'kumar-flaskpipelines'

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UniversalPackages@0
  inputs:
    versionSpec: '3.6'
    architecture: 'x64'

# The | symbol is a continuation character, indicating a multi-line script.
# A single-line script can immediately follows "- script:" without the |.
- script: |
    # antenv is the virtual environment name that App Service expects
    python3.6 -m venv antenv
    source antenv/bin/activate
    pip3.6 install setuptools
    pip3.6 install -r requirements.txt

  # The displayName is shows in the pipeline UI when a build runs
  displayName: 'Install Dependencies'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourceDirectory)'
    includeRootFolder: false
    archiveType: zip
    archiveFile: '$(Build.ArtifactsStagingDirectory)/Application$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: AzureRmWebAppDeployment@4
  displayName: Azure  App Service Deploy
  inputs:
    appType: webAppLinux
    RuntimeStack: 'PYTHON|3.6'
    ConnectedServiceName: $(ConnectedServiceName)
    WebAppName: $(WebAppName)
    Package: '$(Build.ArtifactsStagingDirectory)/Application$(Build.BuildId).zip'
    # The following parameter is specific to the Flask example code. You may
    # or may not need a startup command for your own app.

    StartupCommand: 'gunicorn --bind=0.0.0.0 --workers=4 startup:app'
