variables:
  ConnectedServiceName: 'Azure Primary'
  WebAppName: 'kumar-flaskpipelines'

trigger:
- master

pool:
  name: Hosted Ubuntu 1604

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.6'
    architecture: 'x64'

- script: |
    python3.6 -m venv antenv
    source antenv/bin/activate
    pip3.6 install setuptools
    pip3.6 install -r requirements.txt

  # The displayName is shows in the pipeline UI when a build runs
  displayName: 'Install Dependencies'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/Application$(Build.BuildId).zip'
    replaceExistingArchive: true
    verbose: # Optional

- task: AzureRmWebAppDeployment@4
  displayName: Azure App Service Deploy
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Pay-As-You-Go(f1c62fd3-849e-42dd-9b0f-2fe95f6ce81e)'
    appType: 'webAppLinux'
    WebAppName: 'kumar-flaskpipelines'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
    RuntimeStack: 'PYTHON|3.6'
    StartupCommand: 'gunicorn --bind=0.0.0.0 --workers=4 startup:app'